# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/chrisjerrett/Desktop/Slam

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/chrisjerrett/Desktop/Slam

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/chrisjerrett/Desktop/Slam/CMakeFiles /Users/chrisjerrett/Desktop/Slam/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/chrisjerrett/Desktop/Slam/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Slam

# Build rule for target.
Slam: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Slam
.PHONY : Slam

# fast build rule for target.
Slam/fast:
	$(MAKE) -f CMakeFiles/Slam.dir/build.make CMakeFiles/Slam.dir/build
.PHONY : Slam/fast

src/Calculations.o: src/Calculations.cpp.o

.PHONY : src/Calculations.o

# target to build an object file
src/Calculations.cpp.o:
	$(MAKE) -f CMakeFiles/Slam.dir/build.make CMakeFiles/Slam.dir/src/Calculations.cpp.o
.PHONY : src/Calculations.cpp.o

src/Calculations.i: src/Calculations.cpp.i

.PHONY : src/Calculations.i

# target to preprocess a source file
src/Calculations.cpp.i:
	$(MAKE) -f CMakeFiles/Slam.dir/build.make CMakeFiles/Slam.dir/src/Calculations.cpp.i
.PHONY : src/Calculations.cpp.i

src/Calculations.s: src/Calculations.cpp.s

.PHONY : src/Calculations.s

# target to generate assembly for a file
src/Calculations.cpp.s:
	$(MAKE) -f CMakeFiles/Slam.dir/build.make CMakeFiles/Slam.dir/src/Calculations.cpp.s
.PHONY : src/Calculations.cpp.s

src/Lidar.o: src/Lidar.cpp.o

.PHONY : src/Lidar.o

# target to build an object file
src/Lidar.cpp.o:
	$(MAKE) -f CMakeFiles/Slam.dir/build.make CMakeFiles/Slam.dir/src/Lidar.cpp.o
.PHONY : src/Lidar.cpp.o

src/Lidar.i: src/Lidar.cpp.i

.PHONY : src/Lidar.i

# target to preprocess a source file
src/Lidar.cpp.i:
	$(MAKE) -f CMakeFiles/Slam.dir/build.make CMakeFiles/Slam.dir/src/Lidar.cpp.i
.PHONY : src/Lidar.cpp.i

src/Lidar.s: src/Lidar.cpp.s

.PHONY : src/Lidar.s

# target to generate assembly for a file
src/Lidar.cpp.s:
	$(MAKE) -f CMakeFiles/Slam.dir/build.make CMakeFiles/Slam.dir/src/Lidar.cpp.s
.PHONY : src/Lidar.cpp.s

src/PaintArea.o: src/PaintArea.cpp.o

.PHONY : src/PaintArea.o

# target to build an object file
src/PaintArea.cpp.o:
	$(MAKE) -f CMakeFiles/Slam.dir/build.make CMakeFiles/Slam.dir/src/PaintArea.cpp.o
.PHONY : src/PaintArea.cpp.o

src/PaintArea.i: src/PaintArea.cpp.i

.PHONY : src/PaintArea.i

# target to preprocess a source file
src/PaintArea.cpp.i:
	$(MAKE) -f CMakeFiles/Slam.dir/build.make CMakeFiles/Slam.dir/src/PaintArea.cpp.i
.PHONY : src/PaintArea.cpp.i

src/PaintArea.s: src/PaintArea.cpp.s

.PHONY : src/PaintArea.s

# target to generate assembly for a file
src/PaintArea.cpp.s:
	$(MAKE) -f CMakeFiles/Slam.dir/build.make CMakeFiles/Slam.dir/src/PaintArea.cpp.s
.PHONY : src/PaintArea.cpp.s

src/Roomba.o: src/Roomba.cpp.o

.PHONY : src/Roomba.o

# target to build an object file
src/Roomba.cpp.o:
	$(MAKE) -f CMakeFiles/Slam.dir/build.make CMakeFiles/Slam.dir/src/Roomba.cpp.o
.PHONY : src/Roomba.cpp.o

src/Roomba.i: src/Roomba.cpp.i

.PHONY : src/Roomba.i

# target to preprocess a source file
src/Roomba.cpp.i:
	$(MAKE) -f CMakeFiles/Slam.dir/build.make CMakeFiles/Slam.dir/src/Roomba.cpp.i
.PHONY : src/Roomba.cpp.i

src/Roomba.s: src/Roomba.cpp.s

.PHONY : src/Roomba.s

# target to generate assembly for a file
src/Roomba.cpp.s:
	$(MAKE) -f CMakeFiles/Slam.dir/build.make CMakeFiles/Slam.dir/src/Roomba.cpp.s
.PHONY : src/Roomba.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Slam.dir/build.make CMakeFiles/Slam.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Slam.dir/build.make CMakeFiles/Slam.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Slam.dir/build.make CMakeFiles/Slam.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Slam"
	@echo "... src/Calculations.o"
	@echo "... src/Calculations.i"
	@echo "... src/Calculations.s"
	@echo "... src/Lidar.o"
	@echo "... src/Lidar.i"
	@echo "... src/Lidar.s"
	@echo "... src/PaintArea.o"
	@echo "... src/PaintArea.i"
	@echo "... src/PaintArea.s"
	@echo "... src/Roomba.o"
	@echo "... src/Roomba.i"
	@echo "... src/Roomba.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

